### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by GuilhermeBalog** [GuilhermeBalog/guilhermebalog.github.io#7]
# To do

Algumas melhorias que quero fazer por aqui

## Seções

- [ ] Terminar a seção de formações
- [ ] Adicionar seção de eventos
- [x] Adicionar seção de experiências profissionais
- [ ] Estilizar as seções acima

## Projetos

- [ ] Colocar imagens num tamanho apropriado
  - [ ] Tirar novas screenshots em tamanho 1200x600
  - [ ] Configurar alguma compressão de imagem
- [ ] Criar Repositórios
  - [ ] QWERTY play
  - [ ] Slider
  - [ ] WhatsApp Link Generator
- [ ] Adicionar projetos
  - [ ] Be The Hero
  - [ ] Bingo
  - [ ] Blog!
  - [ ] Repository Screenshots
  - [ ] Thumbnail Generator
- [ ] Deixar projetos apresentáveis
    - [ ] Adicionar ícone, se for o caso
    - [ ] Adicionar as tags de SEO
    - [ ] Adicionar o print nas tags de preview
    - [ ] Pesquisar sobre expo web ou algo para apresentar os projetos mobile
    - [ ] Be the Hero
      - [x] Deploy do front
      - [x] Deploy do back
      - [x] Tirar Print
      - [ ] Adicionar prints no README
    - [ ] Bingo
      - [ ] Dar um tapa no css
      - [ ] Deploy no github pages
      - [ ] Texto: citar as festas juninas tradicionais na minha região
      - [ ] Tirar print
      - [ ] Adicionar GIF no README
    - [ ] Blog
      - [ ] Adicionar AMP
      - [ ] Mais posts
      - [ ] Colocar o ícone com fundo transparente
      - [ ] Converter para React
      - [ ] Utilizar o componente next/image
    - [ ] Capivara Chat
      - [ ] Separar a parte estática
      - [ ] Deploy no github pages
      - [ ] Dar um tapa no github pages
    - [ ] Dev Radar
      - [ ] Deploy do front
      - [ ] Deploy do back
      - [ ] Apresentação do mobile
      - [ ] Tirar print
      - [ ] Adicionar imagens no README
    - [x] Genius
      - [x] Deixar mais parecido com o brinquedo
      - [x] Botão de play no meio
      - [x] Tirar print
    - [x] Imersão Gamedev
      - [x] Colocar um title
    - [ ] JS Music Keyboard
      - [ ] Sei lá mano
    - [ ] Portfólio Generator
      - [ ] Adicionar filtro de linguagens
      - [ ] Adicionar botão de imprimir
    - [ ] Repository Screenshots
      - [ ] Fazer ferramenta CLI
        - [ ] Opção de tirar de todos os repos
        - [ ] Tirar de um repo específico
        - [ ] Tirar de uma uma URL qualquer
        - [ ] Tirar de uma URL podendo ajustar zoom
        - [ ] Selecionar resolução
        - [ ] Passar o caminho como parâmetro
        - [ ] Publicar no NPM
    - [ ] Thumbnail Generator
      - [ ] Ferramenta CLI
        - [ ] Passar os parâmetros como argumento do comando
        - [ ] Gerar uma só ou várias
    - [ ] Tic Tac Toe
      - [ ] Traduzir pra português
      - [ ] Gerenciar melhor de quem é a vez. Sempre começar no mesmo ou começar quem ganha, ou trocar, algo do tipo.
      - [ ] Verificar a borda
      - [ ] Talvez fazer o design clássico
      - [ ] Adicionar a inteligência artificial
    - [ ] Todo List
      - [ ] Dar um tapa no CSS
    - [ ] Voce Eh Um Gerador
      - [ ] Adicionar filtro de imagens livres na busca do google
      - [ ] Fazer ferramenta CLI
        - [ ] Passar o caminho como argumento
        - [ ] Passar lista de nomes, ou caminho pra JSON?
    - [ ] Wave Separator
      - [ ] É só a imagem de preview mesmo

## Impressão

- [ ] Adicionar botão de impressão do currículo
- [ ] Usar o `media print` do css para mudar algumas coisas, como os cards de projeto
